#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~/loom -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    # Create new session with 4 windows
    tmux new-session -s $selected_name -c $selected -d
    # Create additional windows
    tmux new-window -t $selected_name:2 -c $selected
    tmux new-window -t $selected_name:3 -c $selected -n "tests"
    tmux new-window -t $selected_name:4 -c $selected -n "debug"
    # Switch to first window and attach
    tmux select-window -t $selected_name:1
    tmux attach-session -t $selected_name
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    # Create new detached session with 4 windows
    tmux new-session -ds $selected_name -c $selected
    # Create additional windows
    tmux new-window -t $selected_name:2 -c $selected
    tmux new-window -t $selected_name:3 -c $selected -n "tests"
    tmux new-window -t $selected_name:4 -c $selected -n "debug"
    # Switch to first window
    tmux select-window -t $selected_name:1
fi

tmux switch-client -t $selected_name
